version: '3.4'

services:
  mindverse:
    image: mindverse
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
